export const ADD_OVERVIEW = 'ADD_OVERVIEW'
export const UPDATE_OVERVIEW = 'UPDATE_OVERVIEW'
export const ADD_PLAN = 'ADD_PLAN'
export const UPDATE_PLAN = 'UPDATE_PLAN'
export const ADD_LODGING = 'ADD_LODGING'
export const UPDATE_LODGING = 'UPDATE_LODGING'
export const SAVE_SEARCH = 'SAVE_SEARCH'
export const SAVE_MAP = 'SAVE_MAP'
